templateDir: local-api/generator_custom_templates
additionalProperties:
  projectName: formlabs_local_api
  packageName: formlabs_local_api
  packageVersion: 0.8.7
files:
  PreFormApi.py:
    folder: formlabs_local_api
    destinationFilename: PreFormApi.py
    templateType: SupportingFiles
  __init__package.mustache:
    # Overring the default template:
    # https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/python/__init__package.mustache
    # to add an import of the PreFormApi.py
    folder: formlabs_local_api
    destinationFilename: __init__.py
    templateType: SupportingFiles
